### ISSUE TITLE
"configuration-enabled" should be boolean and have a default value

### ISSUE THREAD

**Issue by bkrrrr** [uxkjaer/ui5-middleware-code-coverage#17]
i set accidentally "configuration-enabled" to true/false and realised the setting is a string.
This is very inconvenient for yml manipulations in a ci

**Comment by bkrrrr** [comment]
i created another middleware with baseline, source-map support & some test... this fixes also this problem.
So i close this issue [ui5-middleware-code-coverage-advanced](https://github.com/bkrrrr/ui5-middleware-code-coverage-advanced)

**Comment by uxkjaer** [comment]
Nice! I've deprecated my package and are referring to yours instead.
