### ISSUE TITLE
Exclude folders

### ISSUE THREAD

**Issue by jberthe** [uxkjaer/ui5-middleware-code-coverage#2]
Hello,

First, thanks for your middleware it helps me a lot.

I would like to know if it was possible to exclude folders from the transpilation ? I would like to exclude the *webapp/test/* forlder.

Regards,
Joseph

**Comment by uxkjaer** [comment]
Hi Joseph,

I've updated the package now with an exclude option. You can exclude folders here. Just comma separate them if you want to add more. 
Do you think a exclude files is needed?

Please pull the latest package and test it out. If you are happy please close the issue.

**Comment by jberthe** [comment]
Very nice, I will test it in the next few days. I will tell you the result.

Thanks for the quick action.

Regards,
Joseph

**Comment by uxkjaer** [comment]
Did you have any success?

**Comment by uxkjaer** [comment]
closing this issue
